Repository ericbrasiln/git-gh-workflow, pull requests merged in 2022-08, with the labels that each got.

#3 Update issue templates
  .github/ISSUE_TEMPLATE/template-padr-o-para-issues.md
Labels: documentation

#4 Create PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 Ericdhlab/issue1and2
  LICENSE
  LICENSE.md
  PH_workflow/README.md
  Proposta-lição-PH/README.md
  README.md
  cronograma.md
  plano_de_trabalho.md
Labels: documentation

#8 Ericdhlab/issue6
  PH_workflow/estrutura_da_analise.md
  bib/scholar.bib
  bib/scopus.bib
Labels: documentation

#10 Levantamento-bib
  bib/README.md
  bib/bibliometrix/biblioshiny.R
  bib/bibliometrix/csvs/Annual_Production.csv
  bib/bibliometrix/csvs/Countries_Production_Over_Time.csv
  bib/bibliometrix/csvs/Country_Production.csv
  bib/bibliometrix/csvs/Main_Information.csv
  bib/bibliometrix/csvs/Most_Cited_Countries.csv
  bib/bibliometrix/csvs/Most_Cited_Sources.csv
  bib/bibliometrix/csvs/Most_Frequent_Words.csv
  bib/bibliometrix/csvs/Most_Frequent_Words_WC_abs_bigrams.csv
  bib/bibliometrix/csvs/Most_Frequent_Words_WC_kwd.csv
  bib/bibliometrix/csvs/Most_Frequent_Words_WC_titles_uni.csv
  bib/bibliometrix/csvs/Most_Global_Cited_Documents.csv
  bib/bibliometrix/csvs/Most_Local_Cited_Authors.csv
  bib/bibliometrix/csvs/Most_Relevant_Affiliations.csv
  bib/bibliometrix/csvs/Most_Relevant_Countries_By_Corresponding_Author.csv
  bib/bibliometrix/csvs/Most_Relevant_Sources.csv
  bib/bibliometrix/csvs/World_Collaboration_Map.csv
  bib/bibliometrix/visualizations/html/Co-citation_Network_authors.html
  bib/bibliometrix/visualizations/html/Co-citation_Network_papers.html
  bib/bibliometrix/visualizations/html/Collaboration_Network_authors.html
  bib/bibliometrix/visualizations/html/Collaboration_Network_countries.html
  bib/bibliometrix/visualizations/html/Collaboration_Network_inst.html
  bib/bibliometrix/visualizations/html/network_abs_bigrams.html
  bib/bibliometrix/visualizations/imgs/AnnualScientificProduction-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/CountryCollaborationMap-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/CountryOverTime-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/CountryScientificProduction-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostCitedCountries-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostGlobalCitedDocuments-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostLocalCitedSources-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostRelevantAffiliations-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostRelevantAuthors-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostRelevantCountries-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostRelevantSources-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/MostRelevantWords-2022-08-17.png
  bib/bibliometrix/visualizations/imgs/Three-Field_Plot.png
  bib/scopus.bib
  cronograma.md
Labels: documentation, bibliografia

#17 Análise das diretrizes do Site
  PH_workflow/Site/Site.bib
  PH_workflow/Site/files/7820/sobre.html
  PH_workflow/Site/files/7822/directrizes-autor.html
  PH_workflow/Site/files/7824/directrizes-revisor.html
  PH_workflow/Site/files/7826/directrizes-editor.html
  PH_workflow/Site/files/7828/formulario.proposta.licao.html
  PH_workflow/Site/files/7833/equipe.html
  PH_workflow/Site/files/7835/pesquisa.html
  PH_workflow/Site/files/7837/politica-de-privacidade.html
  PH_workflow/Site/files/7839/reportar-um-erro.html
  PH_workflow/Site/files/7842/directrizes-tradutor.html
  PH_workflow/Site/files/7844/ppi.html
  PH_workflow/Site/files/7847/apoiadores.html
  PH_workflow/Site/files/7851/vacancies.html
  PH_workflow/Site/files/7853/contribua.html
  PH_workflow/Site/files/7994/licoes-politica-remocao.html
Labels: análise, site
